use lux_hir::{LocalId, TargetEnvironment};

use crate::codegen::lower_to_bytecode;
use crate::lower::lower;
use crate::mir::{MirConstant, MirInstruction, Terminator};

fn lower_source(source: &str) -> crate::mir::MirModule {
    lower_source_with_targets(source, &TargetEnvironment::new())
}

fn lower_source_with_targets(source: &str, targets: &TargetEnvironment) -> crate::mir::MirModule {
    let ast = lux_syntax::parse(source).expect("should parse");
    let hir = lux_hir::lower(&ast, targets).expect("should resolve");
    let typed = lux_typeck::check(&hir).expect("should type check");
    lower(&hir, &typed)
}

#[test]
fn lowers_simple_wait_scene() {
    let module = lower_source("scene main { wait 1s; }");
    assert_eq!(module.functions.len(), 1);
    let main = &module.functions[0];
    assert_eq!(main.name, "main");
    assert_eq!(module.entry, Some(main.id));

    let block = main.entry_block();
    assert_eq!(
        block.instructions,
        vec![
            MirInstruction::Const(MirConstant::Duration(1_000_000_000)),
            MirInstruction::Wait,
        ]
    );
    assert_eq!(block.terminator, Terminator::Return);
}

#[test]
fn lowers_local_duration_wait() {
    let module = lower_source(
        r#"
        scene main {
            let duration = 1s;
            wait duration;
        }
        "#,
    );
    let main = &module.functions[0];
    assert_eq!(main.locals.len(), 1);
    assert_eq!(main.locals[0].ty, lux_typeck::Type::Duration);

    let block = main.entry_block();
    assert_eq!(
        block.instructions,
        vec![
            MirInstruction::Const(MirConstant::Duration(1_000_000_000)),
            MirInstruction::StoreLocal(LocalId(0)),
            MirInstruction::LoadLocal(LocalId(0)),
            MirInstruction::Wait,
        ]
    );
    assert_eq!(block.terminator, Terminator::Return);
}

#[test]
fn lowers_binary_expression_into_push_push_op() {
    let module = lower_source(
        r#"
        scene main {
            let duration = 1s + 500ms;
            wait duration;
        }
        "#,
    );
    let main = &module.functions[0];
    let block = main.entry_block();
    assert_eq!(
        block.instructions,
        vec![
            MirInstruction::Const(MirConstant::Duration(1_000_000_000)),
            MirInstruction::Const(MirConstant::Duration(500_000_000)),
            MirInstruction::Add,
            MirInstruction::StoreLocal(LocalId(0)),
            MirInstruction::LoadLocal(LocalId(0)),
            MirInstruction::Wait,
        ]
    );
}

#[test]
fn negation_desugars_to_zero_minus_operand() {
    let module = lower_source("scene main { let x = -12; }");
    let main = &module.functions[0];
    let block = main.entry_block();
    assert_eq!(
        block.instructions,
        vec![
            MirInstruction::Const(MirConstant::Int(0)),
            MirInstruction::Const(MirConstant::Int(12)),
            MirInstruction::Sub,
            MirInstruction::StoreLocal(LocalId(0)),
        ]
    );
}

#[test]
fn bare_expression_statement_pops_its_value() {
    let module = lower_source("scene main { let x = 1s; x; }");
    let main = &module.functions[0];
    let block = main.entry_block();
    assert_eq!(block.instructions.last(), Some(&MirInstruction::Pop));
}

#[test]
fn scene_not_named_main_is_not_the_entry_point() {
    let module = lower_source("scene intro { wait 1s; }");
    assert_eq!(module.entry, None);
}

#[test]
fn codegen_produces_bytecode_that_verifies() {
    let module = lower_source(
        r#"
        scene main {
            let first: Duration = 1s;
            let second: Duration = 500ms;
            let duration = first + second;

            wait duration;
        }
        "#,
    );
    let bytecode = lower_to_bytecode(&module);
    lux_bytecode::verify(&bytecode).expect("compiler-generated bytecode must verify");
}

#[test]
fn codegen_is_deterministic() {
    let source = r#"
        scene main {
            let a = 1s;
            let b = a + 500ms;
            wait b;
        }
    "#;
    let first = lower_to_bytecode(&lower_source(source));
    let second = lower_to_bytecode(&lower_source(source));
    assert_eq!(first, second);
}

fn washes_environment() -> TargetEnvironment {
    let mut targets = TargetEnvironment::new();
    targets.insert("Washes");
    targets
}

#[test]
fn lowers_attribute_assignment_to_set_attribute() {
    let module = lower_source_with_targets(
        "scene main { Washes.intensity = 50%; }",
        &washes_environment(),
    );
    let main = &module.functions[0];
    let block = main.entry_block();
    assert_eq!(
        block.instructions,
        vec![
            MirInstruction::Const(MirConstant::Intensity(32767)),
            MirInstruction::SetAttribute {
                target: lux_hir::TargetId(0),
                attribute: lux_typeck::Attribute::Intensity
            },
        ]
    );
    assert_eq!(module.target_count, 1);
}

#[test]
fn set_attribute_codegen_produces_bytecode_that_verifies() {
    let module = lower_source_with_targets(
        "scene main { Washes.intensity = 50%; }",
        &washes_environment(),
    );
    let bytecode = lower_to_bytecode(&module);
    assert_eq!(bytecode.target_count, 1);
    lux_bytecode::verify(&bytecode).expect("compiler-generated bytecode must verify");
}

#[test]
fn transition_remains_one_semantic_mir_and_bytecode_operation() {
    let module = lower_source_with_targets(
        "scene main { Washes.intensity -> 100% over 2s; }",
        &washes_environment(),
    );
    assert_eq!(
        module.functions[0].entry_block().instructions,
        vec![
            MirInstruction::Const(MirConstant::Intensity(u16::MAX)),
            MirInstruction::Const(MirConstant::Duration(2_000_000_000)),
            MirInstruction::TransitionAttribute {
                target: lux_hir::TargetId(0),
                attribute: lux_typeck::Attribute::Intensity,
            },
        ]
    );
    let bytecode = lower_to_bytecode(&module);
    assert_eq!(bytecode.functions[0].max_stack, 2);
    assert!(matches!(
        bytecode.functions[0].code[2],
        lux_bytecode::Instruction::TransitionAttribute {
            target: lux_bytecode::TargetId(0),
            attribute: lux_bytecode::Attribute::Intensity,
        }
    ));
    lux_bytecode::verify(&bytecode).unwrap();
}

#[test]
fn lowers_math_sin_call_to_call_intrinsic() {
    let module = lower_source("import std.Math; scene main { let x = Math.sin(90deg); }");
    let block = module.functions[0].entry_block();
    assert_eq!(
        block.instructions,
        vec![
            MirInstruction::Const(MirConstant::Angle(90_000)),
            MirInstruction::CallIntrinsic {
                intrinsic: lux_stdlib::IntrinsicId::MathSin,
                arg_count: 1,
            },
            MirInstruction::StoreLocal(LocalId(0)),
        ]
    );
    let bytecode = lower_to_bytecode(&module);
    lux_bytecode::verify(&bytecode).expect("compiler-generated bytecode must verify");
}

#[test]
fn lowers_color_rgb_call_and_verifies() {
    let module = lower_source("import std.Color; scene main { let x = Color.rgb(255, 120, 20); }");
    let bytecode = lower_to_bytecode(&module);
    assert!(matches!(
        bytecode.functions[0].code[3],
        lux_bytecode::Instruction::CallIntrinsic {
            intrinsic: lux_bytecode::IntrinsicId::ColorRgb,
            arg_count: 3,
        }
    ));
    lux_bytecode::verify(&bytecode).expect("compiler-generated bytecode must verify");
}

#[test]
fn lowers_signal_constant_call_and_verifies() {
    let module = lower_source(
        "import std.Signal; scene main { let s: Signal<Intensity> = Signal.constant(50%); }",
    );
    assert_eq!(
        module.functions[0].locals[0].ty,
        lux_typeck::Type::Signal(lux_typeck::SignalElement::Intensity)
    );
    let bytecode = lower_to_bytecode(&module);
    assert!(matches!(
        bytecode.functions[0].code[1],
        lux_bytecode::Instruction::CallIntrinsic {
            intrinsic: lux_bytecode::IntrinsicId::SignalConstantIntensity,
            arg_count: 1,
        }
    ));
    assert_eq!(
        bytecode.functions[0].locals[0],
        lux_bytecode::ValueType::Signal(lux_bytecode::ScalarValueType::Intensity)
    );
    lux_bytecode::verify(&bytecode).expect("compiler-generated bytecode must verify");
}

#[test]
fn lowers_nested_and_overloaded_stdlib_calls_and_verifies() {
    let module = lower_source(
        r#"
        import std.Math;
        import std.Color;
        scene main {
            let a = Math.clamp(Math.abs(-5), 0, 10);
            let b = Math.abs(-2.5);
            let c = Color.mix(red, blue, Math.lerp(0.0, 1.0, 0.5));
        }
        "#,
    );
    let bytecode = lower_to_bytecode(&module);
    lux_bytecode::verify(&bytecode).expect("compiler-generated bytecode must verify");
}
