use lux_hir::LocalId;

use crate::codegen::lower_to_bytecode;
use crate::lower::lower;
use crate::mir::{MirConstant, MirInstruction, Terminator};

fn lower_source(source: &str) -> crate::mir::MirModule {
    let ast = lux_syntax::parse(source).expect("should parse");
    let hir = lux_hir::lower(&ast).expect("should resolve");
    let typed = lux_typeck::check(&hir).expect("should type check");
    lower(&hir, &typed)
}

#[test]
fn lowers_simple_wait_scene() {
    let module = lower_source("scene main { wait 1s; }");
    assert_eq!(module.functions.len(), 1);
    let main = &module.functions[0];
    assert_eq!(main.name, "main");
    assert_eq!(module.entry, Some(main.id));

    let block = main.entry_block();
    assert_eq!(
        block.instructions,
        vec![
            MirInstruction::Const(MirConstant::Duration(1_000_000_000)),
            MirInstruction::Wait,
        ]
    );
    assert_eq!(block.terminator, Terminator::Return);
}

#[test]
fn lowers_local_duration_wait() {
    let module = lower_source(
        r#"
        scene main {
            let duration = 1s;
            wait duration;
        }
        "#,
    );
    let main = &module.functions[0];
    assert_eq!(main.locals.len(), 1);
    assert_eq!(main.locals[0].ty, lux_typeck::Type::Duration);

    let block = main.entry_block();
    assert_eq!(
        block.instructions,
        vec![
            MirInstruction::Const(MirConstant::Duration(1_000_000_000)),
            MirInstruction::StoreLocal(LocalId(0)),
            MirInstruction::LoadLocal(LocalId(0)),
            MirInstruction::Wait,
        ]
    );
    assert_eq!(block.terminator, Terminator::Return);
}

#[test]
fn lowers_binary_expression_into_push_push_op() {
    let module = lower_source(
        r#"
        scene main {
            let duration = 1s + 500ms;
            wait duration;
        }
        "#,
    );
    let main = &module.functions[0];
    let block = main.entry_block();
    assert_eq!(
        block.instructions,
        vec![
            MirInstruction::Const(MirConstant::Duration(1_000_000_000)),
            MirInstruction::Const(MirConstant::Duration(500_000_000)),
            MirInstruction::Add,
            MirInstruction::StoreLocal(LocalId(0)),
            MirInstruction::LoadLocal(LocalId(0)),
            MirInstruction::Wait,
        ]
    );
}

#[test]
fn negation_desugars_to_zero_minus_operand() {
    let module = lower_source("scene main { let x = -12; }");
    let main = &module.functions[0];
    let block = main.entry_block();
    assert_eq!(
        block.instructions,
        vec![
            MirInstruction::Const(MirConstant::Int(0)),
            MirInstruction::Const(MirConstant::Int(12)),
            MirInstruction::Sub,
            MirInstruction::StoreLocal(LocalId(0)),
        ]
    );
}

#[test]
fn bare_expression_statement_pops_its_value() {
    let module = lower_source("scene main { let x = 1s; x; }");
    let main = &module.functions[0];
    let block = main.entry_block();
    assert_eq!(block.instructions.last(), Some(&MirInstruction::Pop));
}

#[test]
fn scene_not_named_main_is_not_the_entry_point() {
    let module = lower_source("scene intro { wait 1s; }");
    assert_eq!(module.entry, None);
}

#[test]
fn codegen_produces_bytecode_that_verifies() {
    let module = lower_source(
        r#"
        scene main {
            let first: Duration = 1s;
            let second: Duration = 500ms;
            let duration = first + second;

            wait duration;
        }
        "#,
    );
    let bytecode = lower_to_bytecode(&module);
    lux_bytecode::verify(&bytecode).expect("compiler-generated bytecode must verify");
}

#[test]
fn codegen_is_deterministic() {
    let source = r#"
        scene main {
            let a = 1s;
            let b = a + 500ms;
            wait b;
        }
    "#;
    let first = lower_to_bytecode(&lower_source(source));
    let second = lower_to_bytecode(&lower_source(source));
    assert_eq!(first, second);
}
