//! Facade orchestrating the full Lux compiler pipeline:
//! `source -> parse -> lower HIR -> resolve -> type check -> lower MIR ->
//! codegen -> verify`.
//!
//! This is the only crate downstream tools (CLI, LSP, Studio) should
//! depend on for compiler behavior, per the workspace's "single source of
//! truth" rule — it doesn't add any semantics of its own, only wires the
//! stages together and normalizes their diagnostics into one type.
//!
//! `compile` stops at a verified portable [`BytecodeModule`]; physical fixture
//! and DMX resolution belongs to `inception-linker`.

pub mod diagnostic;
pub mod program;

pub use diagnostic::{Diagnostic, Stage};
pub use lux_bytecode::BytecodeModule;
pub use lux_hir::{HirFile, TargetEnvironment, TargetId};
pub use lux_typeck::TypedProgram;
pub use program::{ProgramSources, SourceUnit, check_program, compile_program};

/// The result of successfully checking a Lux program: its fully resolved
/// and type-checked HIR, plus the type information [`lux_mir::lower`]
/// needs to turn it into MIR.
#[derive(Debug, Clone, PartialEq)]
pub struct CheckedProgram {
    pub hir: HirFile,
    pub typed: TypedProgram,
}

/// Runs the frontend pipeline over `source`: parse, resolve, type check.
/// On success, every scene has been parsed, every name resolved and
/// every expression type checked. On failure, returns every diagnostic
/// collected by whichever stage failed first — parsing and resolution
/// stages don't proceed to the next stage once they've failed, since a
/// later stage can't meaningfully run over a tree it knows is malformed.
///
/// `targets` resolves the target names an `<target>.<attribute> = ...;`
/// assignment can reference (e.g. `Washes` in `Washes.intensity = 50%;`).
/// Portable shows should use a source-level `rig contract` and
/// [`compile_portable`]. `targets` remains useful for isolated compiler tests
/// and compatibility with contract-less source.
pub fn check(source: &str, targets: &TargetEnvironment) -> Result<CheckedProgram, Vec<Diagnostic>> {
    let ast = lux_syntax::parse(source).map_err(diagnostic::from_syntax_errors)?;
    let hir = lux_hir::lower(&ast, targets).map_err(diagnostic::from_hir_errors)?;
    let typed = lux_typeck::check(&hir).map_err(diagnostic::from_type_errors)?;
    Ok(CheckedProgram { hir, typed })
}

/// Compiles `source` all the way down to a verified, in-memory
/// [`BytecodeModule`]: [`check`], then lowers the checked program through
/// `lux-mir` into MIR, generates bytecode, and verifies that bytecode
/// before returning it. See [`check`] for what `targets` is.
///
/// The compiler never hands back bytecode it hasn't verified itself. If
/// verification ever fails here, that means the compiler generated
/// invalid bytecode from a program it had already accepted — a compiler
/// bug, not something the caller's source is responsible for — so it's
/// reported as a single `Stage::Internal` diagnostic rather than the
/// verifier's raw errors, which aren't meaningful to a Lux program
/// author.
pub fn compile(
    source: &str,
    targets: &TargetEnvironment,
) -> Result<BytecodeModule, Vec<Diagnostic>> {
    let checked = check(source, targets)?;
    let mir = lux_mir::lower(&checked.hir, &checked.typed);
    let bytecode = lux_mir::lower_to_bytecode(&mir);

    match lux_bytecode::verify(&bytecode) {
        Ok(()) => Ok(bytecode),
        Err(errors) => Err(vec![Diagnostic::internal(format!(
            "internal compiler error: generated bytecode failed verification: {errors:?}"
        ))]),
    }
}

/// Compiles a portable Lux show whose lighting targets are declared by its
/// `rig contract`. No venue, fixture, patch, or binding information is needed
/// at compile time; those are supplied later to `inception-linker`.
pub fn compile_portable(source: &str) -> Result<BytecodeModule, Vec<Diagnostic>> {
    compile(source, &TargetEnvironment::new())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn no_targets() -> TargetEnvironment {
        TargetEnvironment::new()
    }

    fn washes_environment() -> TargetEnvironment {
        let mut targets = TargetEnvironment::new();
        targets.insert("Washes");
        targets
    }

    #[test]
    fn minimal_scene_compiles() {
        let source = r#"
            scene main {
                wait 1s;
            }
        "#;
        assert!(check(source, &no_targets()).is_ok());
    }

    #[test]
    fn typed_duration_compiles() {
        let source = r#"
            scene main {
                let duration: Duration = 1s;
                wait duration;
            }
        "#;
        check(source, &no_targets()).expect("should type check");
    }

    #[test]
    fn intensity_annotation_mismatch_reports_multiple_diagnostics() {
        let source = r#"
            scene main {
                let duration: Intensity = 150%;
                wait duration;
            }
        "#;
        let diagnostics = check(source, &no_targets()).expect_err("should fail type checking");
        assert!(diagnostics.iter().all(|d| d.stage == Stage::Type));
        assert!(
            diagnostics
                .iter()
                .any(|d| d.message.contains("out of range"))
        );
        assert!(
            diagnostics
                .iter()
                .any(|d| d.message.contains("`wait` expects `Duration`"))
        );
    }

    #[test]
    fn syntax_errors_short_circuit_before_resolution() {
        let source = "scene main { wait; }";
        let diagnostics = check(source, &no_targets()).expect_err("should fail parsing");
        assert!(diagnostics.iter().all(|d| d.stage == Stage::Syntax));
    }

    #[test]
    fn unknown_name_is_a_resolve_diagnostic() {
        let source = "scene main { wait missing; }";
        let diagnostics = check(source, &no_targets()).expect_err("should fail resolution");
        assert!(diagnostics.iter().all(|d| d.stage == Stage::Resolve));
        assert!(
            diagnostics
                .iter()
                .any(|d| d.message.contains("unknown name `missing`"))
        );
    }

    #[test]
    fn compiles_simple_wait_scene() {
        let source = r#"
            scene main {
                wait 1s;
            }
        "#;
        let module = compile(source, &no_targets()).expect("program should compile");
        lux_bytecode::verify(&module).expect("compiler must generate valid bytecode");
    }

    #[test]
    fn compiles_local_duration() {
        let source = r#"
            scene main {
                let duration: Duration = 1s;
                wait duration;
            }
        "#;
        let module = compile(source, &no_targets()).unwrap();
        assert!(!module.functions.is_empty());
        lux_bytecode::verify(&module).expect("compiler must generate valid bytecode");
    }

    #[test]
    fn compiles_arithmetic_expression() {
        let source = r#"
            scene main {
                let duration = 1s + 500ms;
                wait duration;
            }
        "#;
        let module = compile(source, &no_targets()).expect("program should compile");
        lux_bytecode::verify(&module).expect("compiler must generate valid bytecode");
    }

    #[test]
    fn worked_example_from_the_task_brief_compiles_and_verifies() {
        let source = r#"
            scene main {
                let first: Duration = 1s;
                let second: Duration = 500ms;
                let duration = first + second;

                wait duration;
            }
        "#;
        let module = compile(source, &no_targets()).expect("program should compile");
        lux_bytecode::verify(&module).expect("compiler must generate valid bytecode");
    }

    #[test]
    fn compile_reports_frontend_diagnostics_without_reaching_codegen() {
        let source = "scene main { wait 50%; }";
        let diagnostics = compile(source, &no_targets()).expect_err("should fail type checking");
        assert!(diagnostics.iter().all(|d| d.stage == Stage::Type));
    }

    #[test]
    fn compiles_attribute_assignment() {
        let source = "scene main { Washes.intensity = 50%; }";
        let module = compile(source, &washes_environment()).expect("program should compile");
        assert_eq!(module.target_count, 1);
        lux_bytecode::verify(&module).expect("compiler must generate valid bytecode");
    }

    #[test]
    fn attribute_type_mismatch_is_a_type_diagnostic_not_a_runtime_one() {
        // item 35 of this milestone's task brief: `Washes.intensity = red;`
        // must fail at type checking, never reach the renderer or VM.
        let source = "scene main { Washes.intensity = red; }";
        let diagnostics =
            compile(source, &washes_environment()).expect_err("should fail type checking");
        assert!(diagnostics.iter().all(|d| d.stage == Stage::Type));
        assert!(
            diagnostics
                .iter()
                .any(|d| d.message.contains("expected `Intensity`, found `Color`"))
        );
    }

    #[test]
    fn unknown_target_is_a_resolve_diagnostic() {
        let source = "scene main { Washes.intensity = 50%; }";
        let diagnostics = compile(source, &no_targets()).expect_err("should fail resolution");
        assert!(diagnostics.iter().all(|d| d.stage == Stage::Resolve));
        assert!(
            diagnostics
                .iter()
                .any(|d| d.message.contains("unknown target `Washes`"))
        );
    }

    #[test]
    fn rig_contract_compiles_without_an_external_target_environment() {
        let module = compile_portable(
            r#"
            rig contract DemoRig {
                role Washes: Group<Color + Intensity>;
            }
            scene main {
                Washes.intensity -> 100% over 2s;
            }
            "#,
        )
        .unwrap();
        assert_eq!(module.target_count, 1);
        let contract = module.rig_contract.unwrap();
        assert_eq!(contract.name, "DemoRig");
        assert_eq!(contract.roles[0].name, "Washes");
        assert!(
            contract.roles[0]
                .required_capabilities
                .contains(lux_bytecode::Capability::Color)
        );
    }
}
