//! Facade orchestrating the full Lux compiler pipeline:
//! `source -> parse -> lower HIR -> resolve -> type check -> lower MIR ->
//! codegen -> verify`.
//!
//! This is the only crate downstream tools (CLI, LSP, Studio) should
//! depend on for compiler behavior, per the workspace's "single source of
//! truth" rule — it doesn't add any semantics of its own, only wires the
//! stages together and normalizes their diagnostics into one type.
//!
//! VM, runtime, DMX, rigs, fixtures and the linker are out of scope here:
//! `compile` stops once it has a verified, in-memory [`BytecodeModule`].

pub mod diagnostic;

pub use diagnostic::{Diagnostic, Stage};
pub use lux_bytecode::BytecodeModule;
pub use lux_hir::HirFile;
pub use lux_typeck::TypedProgram;

/// The result of successfully checking a Lux program: its fully resolved
/// and type-checked HIR, plus the type information [`lux_mir::lower`]
/// needs to turn it into MIR.
#[derive(Debug, Clone, PartialEq)]
pub struct CheckedProgram {
    pub hir: HirFile,
    pub typed: TypedProgram,
}

/// Runs the frontend pipeline over `source`: parse, resolve, type check.
/// On success, every scene has been parsed, every name resolved and
/// every expression type checked. On failure, returns every diagnostic
/// collected by whichever stage failed first — parsing and resolution
/// stages don't proceed to the next stage once they've failed, since a
/// later stage can't meaningfully run over a tree it knows is malformed.
pub fn check(source: &str) -> Result<CheckedProgram, Vec<Diagnostic>> {
    let ast = lux_syntax::parse(source).map_err(diagnostic::from_syntax_errors)?;
    let hir = lux_hir::lower(&ast).map_err(diagnostic::from_hir_errors)?;
    let typed = lux_typeck::check(&hir).map_err(diagnostic::from_type_errors)?;
    Ok(CheckedProgram { hir, typed })
}

/// Compiles `source` all the way down to a verified, in-memory
/// [`BytecodeModule`]: [`check`], then lowers the checked program through
/// `lux-mir` into MIR, generates bytecode, and verifies that bytecode
/// before returning it.
///
/// The compiler never hands back bytecode it hasn't verified itself. If
/// verification ever fails here, that means the compiler generated
/// invalid bytecode from a program it had already accepted — a compiler
/// bug, not something the caller's source is responsible for — so it's
/// reported as a single `Stage::Internal` diagnostic rather than the
/// verifier's raw errors, which aren't meaningful to a Lux program
/// author.
pub fn compile(source: &str) -> Result<BytecodeModule, Vec<Diagnostic>> {
    let checked = check(source)?;
    let mir = lux_mir::lower(&checked.hir, &checked.typed);
    let bytecode = lux_mir::lower_to_bytecode(&mir);

    match lux_bytecode::verify(&bytecode) {
        Ok(()) => Ok(bytecode),
        Err(errors) => Err(vec![Diagnostic::internal(format!(
            "internal compiler error: generated bytecode failed verification: {errors:?}"
        ))]),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn minimal_scene_compiles() {
        let source = r#"
            scene main {
                wait 1s;
            }
        "#;
        assert!(check(source).is_ok());
    }

    #[test]
    fn typed_duration_compiles() {
        let source = r#"
            scene main {
                let duration: Duration = 1s;
                wait duration;
            }
        "#;
        check(source).expect("should type check");
    }

    #[test]
    fn intensity_annotation_mismatch_reports_multiple_diagnostics() {
        let source = r#"
            scene main {
                let duration: Intensity = 150%;
                wait duration;
            }
        "#;
        let diagnostics = check(source).expect_err("should fail type checking");
        assert!(diagnostics.iter().all(|d| d.stage == Stage::Type));
        assert!(
            diagnostics
                .iter()
                .any(|d| d.message.contains("out of range"))
        );
        assert!(
            diagnostics
                .iter()
                .any(|d| d.message.contains("`wait` expects `Duration`"))
        );
    }

    #[test]
    fn syntax_errors_short_circuit_before_resolution() {
        let source = "scene main { wait; }";
        let diagnostics = check(source).expect_err("should fail parsing");
        assert!(diagnostics.iter().all(|d| d.stage == Stage::Syntax));
    }

    #[test]
    fn unknown_name_is_a_resolve_diagnostic() {
        let source = "scene main { wait missing; }";
        let diagnostics = check(source).expect_err("should fail resolution");
        assert!(diagnostics.iter().all(|d| d.stage == Stage::Resolve));
        assert!(
            diagnostics
                .iter()
                .any(|d| d.message.contains("unknown name `missing`"))
        );
    }

    #[test]
    fn compiles_simple_wait_scene() {
        let source = r#"
            scene main {
                wait 1s;
            }
        "#;
        let module = compile(source).expect("program should compile");
        lux_bytecode::verify(&module).expect("compiler must generate valid bytecode");
    }

    #[test]
    fn compiles_local_duration() {
        let source = r#"
            scene main {
                let duration: Duration = 1s;
                wait duration;
            }
        "#;
        let module = compile(source).unwrap();
        assert!(!module.functions.is_empty());
        lux_bytecode::verify(&module).expect("compiler must generate valid bytecode");
    }

    #[test]
    fn compiles_arithmetic_expression() {
        let source = r#"
            scene main {
                let duration = 1s + 500ms;
                wait duration;
            }
        "#;
        let module = compile(source).expect("program should compile");
        lux_bytecode::verify(&module).expect("compiler must generate valid bytecode");
    }

    #[test]
    fn worked_example_from_the_task_brief_compiles_and_verifies() {
        let source = r#"
            scene main {
                let first: Duration = 1s;
                let second: Duration = 500ms;
                let duration = first + second;

                wait duration;
            }
        "#;
        let module = compile(source).expect("program should compile");
        lux_bytecode::verify(&module).expect("compiler must generate valid bytecode");
    }

    #[test]
    fn compile_reports_frontend_diagnostics_without_reaching_codegen() {
        let source = "scene main { wait 50%; }";
        let diagnostics = compile(source).expect_err("should fail type checking");
        assert!(diagnostics.iter().all(|d| d.stage == Stage::Type));
    }
}
