[package]
name = "inception-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
inception-core.workspace = true
inception-linker.workspace = true
inception-renderer.workspace = true
inception-vm.workspace = true

[dev-dependencies]
inception-driver-dmx.workspace = true
lux-compiler.workspace = true
